# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20181018_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeighbourHood',
            new_name='NeighborHood',
        ),
    ]
