# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0003_auto_20181018_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='neighbor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
