# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_neighborhood_neighbor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='neighbor',
            new_name='residents',
        ),
    ]
