# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0005_auto_20181018_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='residents',
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='residents',
            field=models.ManyToManyField(null=True, related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
