# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_auto_20181018_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(choices=[('Mandera', 'Mandera'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Nyamira', 'Nyamira'), ('Nyeri', 'Nyeri')], max_length=50, null=True),
        ),
    ]
