# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_auto_20181018_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='residents',
            field=models.ManyToManyField(related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
    ]
