# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_auto_20181018_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(choices=[('Mandera', 'Mandera'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('hood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='hood.NeighborHood')),
            ],
        ),
    ]
