# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
